apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: pipeline-
  annotations: {pipelines.kubeflow.org/kfp_sdk_version: 1.8.18, pipelines.kubeflow.org/pipeline_compilation_time: '2022-12-22T13:20:47.879195',
    pipelines.kubeflow.org/pipeline_spec: '{"description": "This simple pipeline wants
      to test the custom created components, as well as the CI/CD operations", "name":
      "pipeline"}'}
  labels: {pipelines.kubeflow.org/kfp_sdk_version: 1.8.18}
spec:
  entrypoint: pipeline
  templates:
  - name: kserve-serve
    container:
      args: [--model, /tmp/inputs/input-0/data]
      command: [python, serve_model.py]
      image: jackma00/kserve-serve:latest
    inputs:
      artifacts:
      - {name: train-knn-model-knn_model, path: /tmp/inputs/input-0/data}
    metadata:
      labels:
        pipelines.kubeflow.org/kfp_sdk_version: 1.8.18
        pipelines.kubeflow.org/pipeline-sdk-type: kfp
        pipelines.kubeflow.org/enable_caching: "true"
  - name: load-data
    container:
      command: [python, load_dataset.py]
      image: jackma00/load-dataset:latest
    outputs:
      artifacts:
      - {name: load-data-raw_dataset, path: raw_dataset.csv}
    metadata:
      labels:
        pipelines.kubeflow.org/kfp_sdk_version: 1.8.18
        pipelines.kubeflow.org/pipeline-sdk-type: kfp
        pipelines.kubeflow.org/enable_caching: "true"
  - name: normalize-data
    container:
      args: [--raw_dataset, /tmp/inputs/input-0/data]
      command: [python, normalize_dataset.py]
      image: jackma00/normalize-dataset:latest
    inputs:
      artifacts:
      - {name: load-data-raw_dataset, path: /tmp/inputs/input-0/data}
    outputs:
      artifacts:
      - {name: normalize-data-normalized_dataset, path: normalized_dataset.csv}
    metadata:
      labels:
        pipelines.kubeflow.org/kfp_sdk_version: 1.8.18
        pipelines.kubeflow.org/pipeline-sdk-type: kfp
        pipelines.kubeflow.org/enable_caching: "true"
  - name: pipeline
    dag:
      tasks:
      - name: kserve-serve
        template: kserve-serve
        dependencies: [train-knn-model]
        arguments:
          artifacts:
          - {name: train-knn-model-knn_model, from: '{{tasks.train-knn-model.outputs.artifacts.train-knn-model-knn_model}}'}
      - {name: load-data, template: load-data}
      - name: normalize-data
        template: normalize-data
        dependencies: [load-data]
        arguments:
          artifacts:
          - {name: load-data-raw_dataset, from: '{{tasks.load-data.outputs.artifacts.load-data-raw_dataset}}'}
      - name: train-knn-model
        template: train-knn-model
        dependencies: [normalize-data]
        arguments:
          artifacts:
          - {name: normalize-data-normalized_dataset, from: '{{tasks.normalize-data.outputs.artifacts.normalize-data-normalized_dataset}}'}
  - name: train-knn-model
    container:
      args: [--normalized_dataset, /tmp/inputs/input-0/data]
      command: [python, train_knn.py]
      image: jackma00/train-knn:latest
    inputs:
      artifacts:
      - {name: normalize-data-normalized_dataset, path: /tmp/inputs/input-0/data}
    outputs:
      artifacts:
      - {name: train-knn-model-knn_model, path: knn.pkl}
    metadata:
      labels:
        pipelines.kubeflow.org/kfp_sdk_version: 1.8.18
        pipelines.kubeflow.org/pipeline-sdk-type: kfp
        pipelines.kubeflow.org/enable_caching: "true"
  arguments:
    parameters: []
  serviceAccountName: pipeline-runner
