# Workflow name.
name: CI CD Pipeline

# Run workflow on every push to main branch.
on:
  push:
    branches: [main]

# Workflow's jobs.
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build the Load Data image 
        run: docker build --tag jackma00/load-dataset:latest ./components/data/load-dataset/
      - name: Push the Load Data image to the container registry
        run: docker push jackma00/load-dataset:latest
      
      - name: Build the Normalize Data image 
        run: docker build --tag jackma00/normalize-dataset:latest ./components/data/normalize-dataset/
      - name: Push the Load Data image to the container registry
        run: docker push jackma00/normalize-dataset:latest

      - name: Build the Train knn image
        run: docker build --tag jackma00/train-knn:latest ./components/models/knn/
      - name: Push the Train knn image to the container registry
        run: docker push jackma00/train-knn:latest

      - name: Build the Serve Model image
        run: docker build --tag jackma00/serve-model:latest ./components/serving/kserve/
      - name: Push the Serve Model image to the container registry
        run: docker push jackma00/serve-model:latest
      
      

      

